### ISSUE TITLE
Deal with leap years nicely

### ISSUE THREAD

**Issue by hugovk** [eartle/twolde#13]
The next leap day is 29 February 2016.

**Comment by hugovk** [comment]
Whoops:

```
Next tweet: "Off to a see black metal band in a Hawaiian tiki bar."
Next tweet time: Sat Feb 28 15:17:35 2015 UTC (in 6 hours, 49 minutes, 18 seconds)
Next tweet: "2013 http://t.co/oB2VLRZxTr 2012 http://t.co/fPLI4ItmGy 2010 http://t.co/Ack1asa1pY 2008 http://t.co/j002bt
el3j 2007 http://t.co/rooVEEqber"
Next tweet time: Sun Mar  1 05:00:00 2015 UTC (in 13 hours, 42 minutes, 24 seconds)
Traceback (most recent call last):
  File "scripts\twolde", line 232, in <module>
    main()
  File "scripts\twolde", line 228, in main
    run()
  File "scripts\twolde", line 136, in run
    now, last_year = get_times()
  File "scripts\twolde", line 22, in get_times
    now.minute, now.second, now.microsecond, now.tzinfo)
ValueError: day is out of range for month
```

The next leap day is 29 February 2020.

**Comment by hugovk** [comment]
So on leap day 29 February 2016, it called this:

``` python
    last_year = datetime(now.year - 1, now.month, now.day, now.hour,
                         now.minute, now.second, now.microsecond, now.tzinfo)
```

And  `datetime(2015, February, 29, etc.. )` does not compute.
