### ISSUE TITLE
"Status is over 140 characters"

### ISSUE THREAD

**Issue by hugovk** [eartle/twolde#4]
Windows 7, cmd.exe, latest master of Twolde.

```
Next tweet: "@Alby "It's more than just a typoÔÇª This is a completely diff. [symbol] with a diff. meaning &amp; complet
ely changes the way the formula works""
Next tweet time: Thu Apr 10 21:36:56 2014 UTC (in 285.329 seconds)
Traceback (most recent call last):
  File "twolde.py", line 219, in <module>
    elif sys.argv[1] == "run":
  File "twolde.py", line 186, in run

  File "C:\Python27\lib\sched.py", line 117, in run
    action(*argument)
  File "twolde.py", line 207, in do_tweet
    def do_tweet(api, text, in_reply_to_status_id):
  File "C:\Python27\lib\site-packages\tweepy\api.py", line 193, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "C:\Python27\lib\site-packages\tweepy\binder.py", line 239, in _call
    return method.execute()
  File "C:\Python27\lib\site-packages\tweepy\binder.py", line 223, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: [{u'message': u'Status is over 140 characters.', u'code': 186}]
```

The original tweet:

> @Alby "It's more than just a typo… This is a completely diff. [symbol] with a diff. meaning & completely changes the way the formula works"

https://twitter.com/hugovk/statuses/454372484037771264

The attempted tweet was four characters too long. The original had one to spare.

`ÔÇª` was really `…` and `&amp;` was really `&`.

**Comment by hugovk** [comment]
Another one, similar escaping thing:

```
Next tweet: "@blech re: http://t.co/fmpuur5Ysn &gt; shows a similar standardisation &gt; https://t.co/vD8fGADHKU Perhaps I should try "decennial sampling" too."
```
