### ISSUE TITLE
Duplicate status error

### ISSUE THREAD

**Issue by hugovk** [eartle/twolde#9]
```
Next tweet: "@OED @OxfordWords "Twitter Posting 25 Aug. in twitter. com (O.E.D. Archive)" is like crediting a book's pub
lisher but not the author."
Next tweet time: Wed Jul  2 11:53:52 2014 UTC (in 4 minutes, 17 seconds)
Next tweet: "GOOD NEWS! I lost the key for my old bicycle in the snow four years ago but I just found the spare in a sho
ebox at the back of a cupboard!"
Next tweet time: Wed Jul  2 18:21:25 2014 UTC (in 6 hours, 27 minutes, 32 seconds)
Traceback (most recent call last):
  File "C:\Users\hugovk\github\twolde\twolde.py", line 234, in <module>
    run()
  File "C:\Users\hugovk\github\twolde\twolde.py", line 185, in run
    s.run()
  File "C:\Python27\lib\sched.py", line 117, in run
    action(*argument)
  File "C:\Users\hugovk\github\twolde\twolde.py", line 206, in do_tweet
    api.update_status(status=text, in_reply_to_status_id=in_reply_to_status_id)
  File "C:\Python27\lib\site-packages\tweepy\api.py", line 193, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "C:\Python27\lib\site-packages\tweepy\binder.py", line 239, in _call
    return method.execute()
  File "C:\Python27\lib\site-packages\tweepy\binder.py", line 223, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: [{u'message': u'Status is a duplicate.', u'code': 187}]
```

That first one [was posted](https://twitter.com/hugonevk/status/616575499817590784) and [is the last one posted](https://twitter.com/hugonevk/with_replies), but the second one didn't make it.

Doesn't look like a duplicate to me.

Anyway, perhaps a `try:` ... `except tweepy.error.TweepError:` is in order, and perhaps for a greater range of exceptions. On exception, print error and either try again X times, or just skip it and carry on.

**Comment by hugovk** [comment]
Hooray, zero open issues with twolde! I declare it bug free ;)
